//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `serialization.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serialization;

/** @hidden */
public class _STestPrxI extends com.zeroc.Ice._ObjectPrxI implements STestPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
