//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `serialization.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serialization;

/**
 * Helper class for marshaling/unmarshaling FiveDoublesSeq.
 **/
public final class FiveDoublesSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, FiveDoubles[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                FiveDoubles.ice_write(ostr, v[i0]);
            }
        }
    }

    public static FiveDoubles[] read(com.zeroc.Ice.InputStream istr)
    {
        final FiveDoubles[] v;
        final int len0 = istr.readAndCheckSeqSize(40);
        v = new FiveDoubles[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = FiveDoubles.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<FiveDoubles[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, FiveDoubles[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 40 + 5 : optSize * 40 + 1);
            FiveDoublesSeqHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<FiveDoubles[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            FiveDoubles[] v;
            v = FiveDoublesSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
