//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `serialization.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serialization;

public class FiveDoubles implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public double d0;

    public double d1;

    public double d2;

    public double d3;

    public double d4;

    public FiveDoubles()
    {
    }

    public FiveDoubles(double d0, double d1, double d2, double d3, double d4)
    {
        this.d0 = d0;
        this.d1 = d1;
        this.d2 = d2;
        this.d3 = d3;
        this.d4 = d4;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FiveDoubles r = null;
        if(rhs instanceof FiveDoubles)
        {
            r = (FiveDoubles)rhs;
        }

        if(r != null)
        {
            if(this.d0 != r.d0)
            {
                return false;
            }
            if(this.d1 != r.d1)
            {
                return false;
            }
            if(this.d2 != r.d2)
            {
                return false;
            }
            if(this.d3 != r.d3)
            {
                return false;
            }
            if(this.d4 != r.d4)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Serialization::FiveDoubles");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, d0);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, d1);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, d2);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, d3);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, d4);
        return h_;
    }

    public FiveDoubles clone()
    {
        FiveDoubles c = null;
        try
        {
            c = (FiveDoubles)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeDouble(this.d0);
        ostr.writeDouble(this.d1);
        ostr.writeDouble(this.d2);
        ostr.writeDouble(this.d3);
        ostr.writeDouble(this.d4);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.d0 = istr.readDouble();
        this.d1 = istr.readDouble();
        this.d2 = istr.readDouble();
        this.d3 = istr.readDouble();
        this.d4 = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, FiveDoubles v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public FiveDoubles ice_read(com.zeroc.Ice.InputStream istr)
    {
        FiveDoubles v = new FiveDoubles();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<FiveDoubles> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, FiveDoubles v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(40);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<FiveDoubles> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(FiveDoubles.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final FiveDoubles _nullMarshalValue = new FiveDoubles();

    /** @hidden */
    public static final long serialVersionUID = 1911761608L;
}
