//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `serialization.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serialization;

public class Person implements java.lang.Cloneable,
                               java.io.Serializable
{
    public String name;

    public String surname;

    public int birthYear;

    public Person()
    {
        this.name = "";
        this.surname = "";
    }

    public Person(String name, String surname, int birthYear)
    {
        this.name = name;
        this.surname = surname;
        this.birthYear = birthYear;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Person r = null;
        if(rhs instanceof Person)
        {
            r = (Person)rhs;
        }

        if(r != null)
        {
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.surname != r.surname)
            {
                if(this.surname == null || r.surname == null || !this.surname.equals(r.surname))
                {
                    return false;
                }
            }
            if(this.birthYear != r.birthYear)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Serialization::Person");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, surname);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, birthYear);
        return h_;
    }

    public Person clone()
    {
        Person c = null;
        try
        {
            c = (Person)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.name);
        ostr.writeString(this.surname);
        ostr.writeInt(this.birthYear);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.name = istr.readString();
        this.surname = istr.readString();
        this.birthYear = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Person v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Person ice_read(com.zeroc.Ice.InputStream istr)
    {
        Person v = new Person();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Person> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Person v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Person> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Person.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Person _nullMarshalValue = new Person();

    /** @hidden */
    public static final long serialVersionUID = -232997239L;
}
