//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `serialization.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Serialization;

public interface STestPrx extends com.zeroc.Ice.ObjectPrx
{
    default void setDummy()
    {
        setDummy(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setDummy(java.util.Map<String, String> context)
    {
        _iceI_setDummyAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setDummyAsync()
    {
        return _iceI_setDummyAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setDummyAsync(java.util.Map<String, String> context)
    {
        return _iceI_setDummyAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setDummyAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setDummy", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void setPerson(Person p)
    {
        setPerson(p, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setPerson(Person p, java.util.Map<String, String> context)
    {
        _iceI_setPersonAsync(p, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setPersonAsync(Person p)
    {
        return _iceI_setPersonAsync(p, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setPersonAsync(Person p, java.util.Map<String, String> context)
    {
        return _iceI_setPersonAsync(p, context, false);
    }

    /**
     * @hidden
     * @param iceP_p -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setPersonAsync(Person iceP_p, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setPerson", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Person.ice_write(ostr, iceP_p);
                 }, null);
        return f;
    }

    default void setPersonSequence(Person[] ps)
    {
        setPersonSequence(ps, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setPersonSequence(Person[] ps, java.util.Map<String, String> context)
    {
        _iceI_setPersonSequenceAsync(ps, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setPersonSequenceAsync(Person[] ps)
    {
        return _iceI_setPersonSequenceAsync(ps, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setPersonSequenceAsync(Person[] ps, java.util.Map<String, String> context)
    {
        return _iceI_setPersonSequenceAsync(ps, context, false);
    }

    /**
     * @hidden
     * @param iceP_ps -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setPersonSequenceAsync(Person[] iceP_ps, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setPersonSequence", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     PersonSeqHelper.write(ostr, iceP_ps);
                 }, null);
        return f;
    }

    default void setFiveDoubles(FiveDoubles fd)
    {
        setFiveDoubles(fd, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setFiveDoubles(FiveDoubles fd, java.util.Map<String, String> context)
    {
        _iceI_setFiveDoublesAsync(fd, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setFiveDoublesAsync(FiveDoubles fd)
    {
        return _iceI_setFiveDoublesAsync(fd, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setFiveDoublesAsync(FiveDoubles fd, java.util.Map<String, String> context)
    {
        return _iceI_setFiveDoublesAsync(fd, context, false);
    }

    /**
     * @hidden
     * @param iceP_fd -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setFiveDoublesAsync(FiveDoubles iceP_fd, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setFiveDoubles", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     FiveDoubles.ice_write(ostr, iceP_fd);
                 }, null);
        return f;
    }

    default void setFiveDoublesSequence(FiveDoubles[] fds)
    {
        setFiveDoublesSequence(fds, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setFiveDoublesSequence(FiveDoubles[] fds, java.util.Map<String, String> context)
    {
        _iceI_setFiveDoublesSequenceAsync(fds, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setFiveDoublesSequenceAsync(FiveDoubles[] fds)
    {
        return _iceI_setFiveDoublesSequenceAsync(fds, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setFiveDoublesSequenceAsync(FiveDoubles[] fds, java.util.Map<String, String> context)
    {
        return _iceI_setFiveDoublesSequenceAsync(fds, context, false);
    }

    /**
     * @hidden
     * @param iceP_fds -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setFiveDoublesSequenceAsync(FiveDoubles[] iceP_fds, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setFiveDoublesSequence", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     FiveDoublesSeqHelper.write(ostr, iceP_fds);
                 }, null);
        return f;
    }

    default void setMixed(Mixed m)
    {
        setMixed(m, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setMixed(Mixed m, java.util.Map<String, String> context)
    {
        _iceI_setMixedAsync(m, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setMixedAsync(Mixed m)
    {
        return _iceI_setMixedAsync(m, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setMixedAsync(Mixed m, java.util.Map<String, String> context)
    {
        return _iceI_setMixedAsync(m, context, false);
    }

    /**
     * @hidden
     * @param iceP_m -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setMixedAsync(Mixed iceP_m, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setMixed", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Mixed.ice_write(ostr, iceP_m);
                 }, null);
        return f;
    }

    default void setMixedSequence(Mixed[] ms)
    {
        setMixedSequence(ms, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setMixedSequence(Mixed[] ms, java.util.Map<String, String> context)
    {
        _iceI_setMixedSequenceAsync(ms, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setMixedSequenceAsync(Mixed[] ms)
    {
        return _iceI_setMixedSequenceAsync(ms, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setMixedSequenceAsync(Mixed[] ms, java.util.Map<String, String> context)
    {
        return _iceI_setMixedSequenceAsync(ms, context, false);
    }

    /**
     * @hidden
     * @param iceP_ms -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setMixedSequenceAsync(Mixed[] iceP_ms, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setMixedSequence", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     MixedSeqHelper.write(ostr, iceP_ms);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static STestPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), STestPrx.class, _STestPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static STestPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), STestPrx.class, _STestPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static STestPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), STestPrx.class, _STestPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static STestPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), STestPrx.class, _STestPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static STestPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, STestPrx.class, _STestPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static STestPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, STestPrx.class, _STestPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default STestPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (STestPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default STestPrx ice_adapterId(String newAdapterId)
    {
        return (STestPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default STestPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (STestPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default STestPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (STestPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default STestPrx ice_invocationTimeout(int newTimeout)
    {
        return (STestPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default STestPrx ice_connectionCached(boolean newCache)
    {
        return (STestPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default STestPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (STestPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default STestPrx ice_secure(boolean b)
    {
        return (STestPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default STestPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (STestPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default STestPrx ice_preferSecure(boolean b)
    {
        return (STestPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default STestPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (STestPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default STestPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (STestPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default STestPrx ice_collocationOptimized(boolean b)
    {
        return (STestPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default STestPrx ice_twoway()
    {
        return (STestPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default STestPrx ice_oneway()
    {
        return (STestPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default STestPrx ice_batchOneway()
    {
        return (STestPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default STestPrx ice_datagram()
    {
        return (STestPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default STestPrx ice_batchDatagram()
    {
        return (STestPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default STestPrx ice_compress(boolean co)
    {
        return (STestPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default STestPrx ice_timeout(int t)
    {
        return (STestPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default STestPrx ice_connectionId(String connectionId)
    {
        return (STestPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default STestPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (STestPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Serialization::STest";
    }
}
