// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_proto.proto

package ser.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stest.Empty)
    com.google.protobuf.MessageOrBuilder {
}
