// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_proto.proto

package ser.grpc;

/**
 * Protobuf type {@code stest.FiveDoubles}
 */
public final class FiveDoubles extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stest.FiveDoubles)
    FiveDoublesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FiveDoubles.newBuilder() to construct.
  private FiveDoubles(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FiveDoubles() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FiveDoubles();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ser.grpc.STestProto.internal_static_stest_FiveDoubles_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ser.grpc.STestProto.internal_static_stest_FiveDoubles_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ser.grpc.FiveDoubles.class, ser.grpc.FiveDoubles.Builder.class);
  }

  public static final int D0_FIELD_NUMBER = 1;
  private double d0_ = 0D;
  /**
   * <code>double d0 = 1;</code>
   * @return The d0.
   */
  @java.lang.Override
  public double getD0() {
    return d0_;
  }

  public static final int D1_FIELD_NUMBER = 2;
  private double d1_ = 0D;
  /**
   * <code>double d1 = 2;</code>
   * @return The d1.
   */
  @java.lang.Override
  public double getD1() {
    return d1_;
  }

  public static final int D2_FIELD_NUMBER = 3;
  private double d2_ = 0D;
  /**
   * <code>double d2 = 3;</code>
   * @return The d2.
   */
  @java.lang.Override
  public double getD2() {
    return d2_;
  }

  public static final int D3_FIELD_NUMBER = 4;
  private double d3_ = 0D;
  /**
   * <code>double d3 = 4;</code>
   * @return The d3.
   */
  @java.lang.Override
  public double getD3() {
    return d3_;
  }

  public static final int D4_FIELD_NUMBER = 5;
  private double d4_ = 0D;
  /**
   * <code>double d4 = 5;</code>
   * @return The d4.
   */
  @java.lang.Override
  public double getD4() {
    return d4_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(d0_) != 0) {
      output.writeDouble(1, d0_);
    }
    if (java.lang.Double.doubleToRawLongBits(d1_) != 0) {
      output.writeDouble(2, d1_);
    }
    if (java.lang.Double.doubleToRawLongBits(d2_) != 0) {
      output.writeDouble(3, d2_);
    }
    if (java.lang.Double.doubleToRawLongBits(d3_) != 0) {
      output.writeDouble(4, d3_);
    }
    if (java.lang.Double.doubleToRawLongBits(d4_) != 0) {
      output.writeDouble(5, d4_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(d0_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, d0_);
    }
    if (java.lang.Double.doubleToRawLongBits(d1_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, d1_);
    }
    if (java.lang.Double.doubleToRawLongBits(d2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, d2_);
    }
    if (java.lang.Double.doubleToRawLongBits(d3_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, d3_);
    }
    if (java.lang.Double.doubleToRawLongBits(d4_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, d4_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ser.grpc.FiveDoubles)) {
      return super.equals(obj);
    }
    ser.grpc.FiveDoubles other = (ser.grpc.FiveDoubles) obj;

    if (java.lang.Double.doubleToLongBits(getD0())
        != java.lang.Double.doubleToLongBits(
            other.getD0())) return false;
    if (java.lang.Double.doubleToLongBits(getD1())
        != java.lang.Double.doubleToLongBits(
            other.getD1())) return false;
    if (java.lang.Double.doubleToLongBits(getD2())
        != java.lang.Double.doubleToLongBits(
            other.getD2())) return false;
    if (java.lang.Double.doubleToLongBits(getD3())
        != java.lang.Double.doubleToLongBits(
            other.getD3())) return false;
    if (java.lang.Double.doubleToLongBits(getD4())
        != java.lang.Double.doubleToLongBits(
            other.getD4())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + D0_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getD0()));
    hash = (37 * hash) + D1_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getD1()));
    hash = (37 * hash) + D2_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getD2()));
    hash = (37 * hash) + D3_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getD3()));
    hash = (37 * hash) + D4_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getD4()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ser.grpc.FiveDoubles parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ser.grpc.FiveDoubles parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ser.grpc.FiveDoubles parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ser.grpc.FiveDoubles parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ser.grpc.FiveDoubles parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ser.grpc.FiveDoubles parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ser.grpc.FiveDoubles parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ser.grpc.FiveDoubles parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ser.grpc.FiveDoubles parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ser.grpc.FiveDoubles parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ser.grpc.FiveDoubles parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ser.grpc.FiveDoubles parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ser.grpc.FiveDoubles prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stest.FiveDoubles}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stest.FiveDoubles)
      ser.grpc.FiveDoublesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.grpc.STestProto.internal_static_stest_FiveDoubles_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.grpc.STestProto.internal_static_stest_FiveDoubles_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.grpc.FiveDoubles.class, ser.grpc.FiveDoubles.Builder.class);
    }

    // Construct using ser.grpc.FiveDoubles.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      d0_ = 0D;
      d1_ = 0D;
      d2_ = 0D;
      d3_ = 0D;
      d4_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ser.grpc.STestProto.internal_static_stest_FiveDoubles_descriptor;
    }

    @java.lang.Override
    public ser.grpc.FiveDoubles getDefaultInstanceForType() {
      return ser.grpc.FiveDoubles.getDefaultInstance();
    }

    @java.lang.Override
    public ser.grpc.FiveDoubles build() {
      ser.grpc.FiveDoubles result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ser.grpc.FiveDoubles buildPartial() {
      ser.grpc.FiveDoubles result = new ser.grpc.FiveDoubles(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ser.grpc.FiveDoubles result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.d0_ = d0_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.d1_ = d1_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.d2_ = d2_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.d3_ = d3_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.d4_ = d4_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ser.grpc.FiveDoubles) {
        return mergeFrom((ser.grpc.FiveDoubles)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ser.grpc.FiveDoubles other) {
      if (other == ser.grpc.FiveDoubles.getDefaultInstance()) return this;
      if (other.getD0() != 0D) {
        setD0(other.getD0());
      }
      if (other.getD1() != 0D) {
        setD1(other.getD1());
      }
      if (other.getD2() != 0D) {
        setD2(other.getD2());
      }
      if (other.getD3() != 0D) {
        setD3(other.getD3());
      }
      if (other.getD4() != 0D) {
        setD4(other.getD4());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              d0_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              d1_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              d2_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              d3_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              d4_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double d0_ ;
    /**
     * <code>double d0 = 1;</code>
     * @return The d0.
     */
    @java.lang.Override
    public double getD0() {
      return d0_;
    }
    /**
     * <code>double d0 = 1;</code>
     * @param value The d0 to set.
     * @return This builder for chaining.
     */
    public Builder setD0(double value) {

      d0_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double d0 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearD0() {
      bitField0_ = (bitField0_ & ~0x00000001);
      d0_ = 0D;
      onChanged();
      return this;
    }

    private double d1_ ;
    /**
     * <code>double d1 = 2;</code>
     * @return The d1.
     */
    @java.lang.Override
    public double getD1() {
      return d1_;
    }
    /**
     * <code>double d1 = 2;</code>
     * @param value The d1 to set.
     * @return This builder for chaining.
     */
    public Builder setD1(double value) {

      d1_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double d1 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearD1() {
      bitField0_ = (bitField0_ & ~0x00000002);
      d1_ = 0D;
      onChanged();
      return this;
    }

    private double d2_ ;
    /**
     * <code>double d2 = 3;</code>
     * @return The d2.
     */
    @java.lang.Override
    public double getD2() {
      return d2_;
    }
    /**
     * <code>double d2 = 3;</code>
     * @param value The d2 to set.
     * @return This builder for chaining.
     */
    public Builder setD2(double value) {

      d2_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double d2 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearD2() {
      bitField0_ = (bitField0_ & ~0x00000004);
      d2_ = 0D;
      onChanged();
      return this;
    }

    private double d3_ ;
    /**
     * <code>double d3 = 4;</code>
     * @return The d3.
     */
    @java.lang.Override
    public double getD3() {
      return d3_;
    }
    /**
     * <code>double d3 = 4;</code>
     * @param value The d3 to set.
     * @return This builder for chaining.
     */
    public Builder setD3(double value) {

      d3_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double d3 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearD3() {
      bitField0_ = (bitField0_ & ~0x00000008);
      d3_ = 0D;
      onChanged();
      return this;
    }

    private double d4_ ;
    /**
     * <code>double d4 = 5;</code>
     * @return The d4.
     */
    @java.lang.Override
    public double getD4() {
      return d4_;
    }
    /**
     * <code>double d4 = 5;</code>
     * @param value The d4 to set.
     * @return This builder for chaining.
     */
    public Builder setD4(double value) {

      d4_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double d4 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearD4() {
      bitField0_ = (bitField0_ & ~0x00000010);
      d4_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stest.FiveDoubles)
  }

  // @@protoc_insertion_point(class_scope:stest.FiveDoubles)
  private static final ser.grpc.FiveDoubles DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ser.grpc.FiveDoubles();
  }

  public static ser.grpc.FiveDoubles getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FiveDoubles>
      PARSER = new com.google.protobuf.AbstractParser<FiveDoubles>() {
    @java.lang.Override
    public FiveDoubles parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FiveDoubles> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FiveDoubles> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ser.grpc.FiveDoubles getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

