// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_proto.proto

package ser.grpc;

public interface FiveDoublesSeqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stest.FiveDoublesSeq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stest.FiveDoubles fiveDoubless = 1;</code>
   */
  java.util.List<ser.grpc.FiveDoubles> 
      getFiveDoublessList();
  /**
   * <code>repeated .stest.FiveDoubles fiveDoubless = 1;</code>
   */
  ser.grpc.FiveDoubles getFiveDoubless(int index);
  /**
   * <code>repeated .stest.FiveDoubles fiveDoubless = 1;</code>
   */
  int getFiveDoublessCount();
  /**
   * <code>repeated .stest.FiveDoubles fiveDoubless = 1;</code>
   */
  java.util.List<? extends ser.grpc.FiveDoublesOrBuilder> 
      getFiveDoublessOrBuilderList();
  /**
   * <code>repeated .stest.FiveDoubles fiveDoubless = 1;</code>
   */
  ser.grpc.FiveDoublesOrBuilder getFiveDoublessOrBuilder(
      int index);
}
