// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_proto.proto

package ser.grpc;

public interface FiveDoublesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stest.FiveDoubles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double d0 = 1;</code>
   * @return The d0.
   */
  double getD0();

  /**
   * <code>double d1 = 2;</code>
   * @return The d1.
   */
  double getD1();

  /**
   * <code>double d2 = 3;</code>
   * @return The d2.
   */
  double getD2();

  /**
   * <code>double d3 = 4;</code>
   * @return The d3.
   */
  double getD3();

  /**
   * <code>double d4 = 5;</code>
   * @return The d4.
   */
  double getD4();
}
