// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_proto.proto

package ser.grpc;

/**
 * Protobuf type {@code stest.Mixed}
 */
public final class Mixed extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stest.Mixed)
    MixedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Mixed.newBuilder() to construct.
  private Mixed(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Mixed() {
    ss_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Mixed();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ser.grpc.STestProto.internal_static_stest_Mixed_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ser.grpc.STestProto.internal_static_stest_Mixed_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ser.grpc.Mixed.class, ser.grpc.Mixed.Builder.class);
  }

  public static final int B_FIELD_NUMBER = 1;
  private int b_ = 0;
  /**
   * <code>uint32 b = 1;</code>
   * @return The b.
   */
  @java.lang.Override
  public int getB() {
    return b_;
  }

  public static final int S_FIELD_NUMBER = 2;
  private int s_ = 0;
  /**
   * <code>int32 s = 2;</code>
   * @return The s.
   */
  @java.lang.Override
  public int getS() {
    return s_;
  }

  public static final int I_FIELD_NUMBER = 3;
  private int i_ = 0;
  /**
   * <code>int32 i = 3;</code>
   * @return The i.
   */
  @java.lang.Override
  public int getI() {
    return i_;
  }

  public static final int F_FIELD_NUMBER = 4;
  private float f_ = 0F;
  /**
   * <code>float f = 4;</code>
   * @return The f.
   */
  @java.lang.Override
  public float getF() {
    return f_;
  }

  public static final int D_FIELD_NUMBER = 5;
  private double d_ = 0D;
  /**
   * <code>double d = 5;</code>
   * @return The d.
   */
  @java.lang.Override
  public double getD() {
    return d_;
  }

  public static final int SS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ss_ = "";
  /**
   * <code>string ss = 6;</code>
   * @return The ss.
   */
  @java.lang.Override
  public java.lang.String getSs() {
    java.lang.Object ref = ss_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ss_ = s;
      return s;
    }
  }
  /**
   * <code>string ss = 6;</code>
   * @return The bytes for ss.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSsBytes() {
    java.lang.Object ref = ss_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ss_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (b_ != 0) {
      output.writeUInt32(1, b_);
    }
    if (s_ != 0) {
      output.writeInt32(2, s_);
    }
    if (i_ != 0) {
      output.writeInt32(3, i_);
    }
    if (java.lang.Float.floatToRawIntBits(f_) != 0) {
      output.writeFloat(4, f_);
    }
    if (java.lang.Double.doubleToRawLongBits(d_) != 0) {
      output.writeDouble(5, d_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ss_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ss_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (b_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, b_);
    }
    if (s_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, s_);
    }
    if (i_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, i_);
    }
    if (java.lang.Float.floatToRawIntBits(f_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, f_);
    }
    if (java.lang.Double.doubleToRawLongBits(d_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, d_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ss_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ss_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ser.grpc.Mixed)) {
      return super.equals(obj);
    }
    ser.grpc.Mixed other = (ser.grpc.Mixed) obj;

    if (getB()
        != other.getB()) return false;
    if (getS()
        != other.getS()) return false;
    if (getI()
        != other.getI()) return false;
    if (java.lang.Float.floatToIntBits(getF())
        != java.lang.Float.floatToIntBits(
            other.getF())) return false;
    if (java.lang.Double.doubleToLongBits(getD())
        != java.lang.Double.doubleToLongBits(
            other.getD())) return false;
    if (!getSs()
        .equals(other.getSs())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + B_FIELD_NUMBER;
    hash = (53 * hash) + getB();
    hash = (37 * hash) + S_FIELD_NUMBER;
    hash = (53 * hash) + getS();
    hash = (37 * hash) + I_FIELD_NUMBER;
    hash = (53 * hash) + getI();
    hash = (37 * hash) + F_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getF());
    hash = (37 * hash) + D_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getD()));
    hash = (37 * hash) + SS_FIELD_NUMBER;
    hash = (53 * hash) + getSs().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ser.grpc.Mixed parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ser.grpc.Mixed parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ser.grpc.Mixed parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ser.grpc.Mixed parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ser.grpc.Mixed parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ser.grpc.Mixed parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ser.grpc.Mixed parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ser.grpc.Mixed parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ser.grpc.Mixed parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ser.grpc.Mixed parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ser.grpc.Mixed parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ser.grpc.Mixed parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ser.grpc.Mixed prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stest.Mixed}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stest.Mixed)
      ser.grpc.MixedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ser.grpc.STestProto.internal_static_stest_Mixed_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ser.grpc.STestProto.internal_static_stest_Mixed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ser.grpc.Mixed.class, ser.grpc.Mixed.Builder.class);
    }

    // Construct using ser.grpc.Mixed.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      b_ = 0;
      s_ = 0;
      i_ = 0;
      f_ = 0F;
      d_ = 0D;
      ss_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ser.grpc.STestProto.internal_static_stest_Mixed_descriptor;
    }

    @java.lang.Override
    public ser.grpc.Mixed getDefaultInstanceForType() {
      return ser.grpc.Mixed.getDefaultInstance();
    }

    @java.lang.Override
    public ser.grpc.Mixed build() {
      ser.grpc.Mixed result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ser.grpc.Mixed buildPartial() {
      ser.grpc.Mixed result = new ser.grpc.Mixed(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ser.grpc.Mixed result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.b_ = b_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.s_ = s_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.i_ = i_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.f_ = f_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.d_ = d_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.ss_ = ss_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ser.grpc.Mixed) {
        return mergeFrom((ser.grpc.Mixed)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ser.grpc.Mixed other) {
      if (other == ser.grpc.Mixed.getDefaultInstance()) return this;
      if (other.getB() != 0) {
        setB(other.getB());
      }
      if (other.getS() != 0) {
        setS(other.getS());
      }
      if (other.getI() != 0) {
        setI(other.getI());
      }
      if (other.getF() != 0F) {
        setF(other.getF());
      }
      if (other.getD() != 0D) {
        setD(other.getD());
      }
      if (!other.getSs().isEmpty()) {
        ss_ = other.ss_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              b_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              s_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              i_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 37: {
              f_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 41: {
              d_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 50: {
              ss_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int b_ ;
    /**
     * <code>uint32 b = 1;</code>
     * @return The b.
     */
    @java.lang.Override
    public int getB() {
      return b_;
    }
    /**
     * <code>uint32 b = 1;</code>
     * @param value The b to set.
     * @return This builder for chaining.
     */
    public Builder setB(int value) {

      b_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 b = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearB() {
      bitField0_ = (bitField0_ & ~0x00000001);
      b_ = 0;
      onChanged();
      return this;
    }

    private int s_ ;
    /**
     * <code>int32 s = 2;</code>
     * @return The s.
     */
    @java.lang.Override
    public int getS() {
      return s_;
    }
    /**
     * <code>int32 s = 2;</code>
     * @param value The s to set.
     * @return This builder for chaining.
     */
    public Builder setS(int value) {

      s_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 s = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearS() {
      bitField0_ = (bitField0_ & ~0x00000002);
      s_ = 0;
      onChanged();
      return this;
    }

    private int i_ ;
    /**
     * <code>int32 i = 3;</code>
     * @return The i.
     */
    @java.lang.Override
    public int getI() {
      return i_;
    }
    /**
     * <code>int32 i = 3;</code>
     * @param value The i to set.
     * @return This builder for chaining.
     */
    public Builder setI(int value) {

      i_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 i = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearI() {
      bitField0_ = (bitField0_ & ~0x00000004);
      i_ = 0;
      onChanged();
      return this;
    }

    private float f_ ;
    /**
     * <code>float f = 4;</code>
     * @return The f.
     */
    @java.lang.Override
    public float getF() {
      return f_;
    }
    /**
     * <code>float f = 4;</code>
     * @param value The f to set.
     * @return This builder for chaining.
     */
    public Builder setF(float value) {

      f_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float f = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearF() {
      bitField0_ = (bitField0_ & ~0x00000008);
      f_ = 0F;
      onChanged();
      return this;
    }

    private double d_ ;
    /**
     * <code>double d = 5;</code>
     * @return The d.
     */
    @java.lang.Override
    public double getD() {
      return d_;
    }
    /**
     * <code>double d = 5;</code>
     * @param value The d to set.
     * @return This builder for chaining.
     */
    public Builder setD(double value) {

      d_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double d = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearD() {
      bitField0_ = (bitField0_ & ~0x00000010);
      d_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object ss_ = "";
    /**
     * <code>string ss = 6;</code>
     * @return The ss.
     */
    public java.lang.String getSs() {
      java.lang.Object ref = ss_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ss_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ss = 6;</code>
     * @return The bytes for ss.
     */
    public com.google.protobuf.ByteString
        getSsBytes() {
      java.lang.Object ref = ss_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ss_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ss = 6;</code>
     * @param value The ss to set.
     * @return This builder for chaining.
     */
    public Builder setSs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ss_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string ss = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSs() {
      ss_ = getDefaultInstance().getSs();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string ss = 6;</code>
     * @param value The bytes for ss to set.
     * @return This builder for chaining.
     */
    public Builder setSsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ss_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stest.Mixed)
  }

  // @@protoc_insertion_point(class_scope:stest.Mixed)
  private static final ser.grpc.Mixed DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ser.grpc.Mixed();
  }

  public static ser.grpc.Mixed getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Mixed>
      PARSER = new com.google.protobuf.AbstractParser<Mixed>() {
    @java.lang.Override
    public Mixed parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Mixed> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Mixed> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ser.grpc.Mixed getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

