// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_proto.proto

package ser.grpc;

public interface MixedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stest.Mixed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 b = 1;</code>
   * @return The b.
   */
  int getB();

  /**
   * <code>int32 s = 2;</code>
   * @return The s.
   */
  int getS();

  /**
   * <code>int32 i = 3;</code>
   * @return The i.
   */
  int getI();

  /**
   * <code>float f = 4;</code>
   * @return The f.
   */
  float getF();

  /**
   * <code>double d = 5;</code>
   * @return The d.
   */
  double getD();

  /**
   * <code>string ss = 6;</code>
   * @return The ss.
   */
  java.lang.String getSs();
  /**
   * <code>string ss = 6;</code>
   * @return The bytes for ss.
   */
  com.google.protobuf.ByteString
      getSsBytes();
}
