// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_proto.proto

package ser.grpc;

public interface MixedSeqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stest.MixedSeq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stest.Mixed mixeds = 1;</code>
   */
  java.util.List<ser.grpc.Mixed> 
      getMixedsList();
  /**
   * <code>repeated .stest.Mixed mixeds = 1;</code>
   */
  ser.grpc.Mixed getMixeds(int index);
  /**
   * <code>repeated .stest.Mixed mixeds = 1;</code>
   */
  int getMixedsCount();
  /**
   * <code>repeated .stest.Mixed mixeds = 1;</code>
   */
  java.util.List<? extends ser.grpc.MixedOrBuilder> 
      getMixedsOrBuilderList();
  /**
   * <code>repeated .stest.Mixed mixeds = 1;</code>
   */
  ser.grpc.MixedOrBuilder getMixedsOrBuilder(
      int index);
}
