// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization_proto.proto

package ser.grpc;

public interface PersonSeqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stest.PersonSeq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stest.Person persons = 1;</code>
   */
  java.util.List<ser.grpc.Person> 
      getPersonsList();
  /**
   * <code>repeated .stest.Person persons = 1;</code>
   */
  ser.grpc.Person getPersons(int index);
  /**
   * <code>repeated .stest.Person persons = 1;</code>
   */
  int getPersonsCount();
  /**
   * <code>repeated .stest.Person persons = 1;</code>
   */
  java.util.List<? extends ser.grpc.PersonOrBuilder> 
      getPersonsOrBuilderList();
  /**
   * <code>repeated .stest.Person persons = 1;</code>
   */
  ser.grpc.PersonOrBuilder getPersonsOrBuilder(
      int index);
}
